﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Trainers;
using Microsoft.ML.Transforms;
using Microsoft.ML;

namespace AutoCow
{
    public partial class MLModel
    {
        /// <summary>
        /// Retrains model using the pipeline generated as part of the training process. For more information on how to load data, see aka.ms/loaddata.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainPipeline(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Categorical.OneHotEncoding(@"breed_type", @"breed_type", outputKind: OneHotEncodingEstimator.OutputKind.Indicator)      
                                    .Append(mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"body_temperature", @"body_temperature"),new InputOutputColumnPair(@"milk_production", @"milk_production"),new InputOutputColumnPair(@"respiratory_rate", @"respiratory_rate"),new InputOutputColumnPair(@"heart_rate", @"heart_rate")}))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"breed_type",@"body_temperature",@"milk_production",@"respiratory_rate",@"heart_rate"}))      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(outputColumnName:@"health_status",inputColumnName:@"health_status"))      
                                    .Append(mlContext.MulticlassClassification.Trainers.OneVersusAll(binaryEstimator:mlContext.BinaryClassification.Trainers.FastTree(new FastTreeBinaryTrainer.Options(){NumberOfLeaves=4,MinimumExampleCountPerLeaf=11,NumberOfTrees=87,MaximumBinCountPerFeature=298,FeatureFraction=0.767160343988858,LearningRate=0.999999776672986,LabelColumnName=@"health_status",FeatureColumnName=@"Features"}),labelColumnName: @"health_status"))      
                                    .Append(mlContext.Transforms.Conversion.MapKeyToValue(outputColumnName:@"PredictedLabel",inputColumnName:@"PredictedLabel"));

            return pipeline;
        }
    }
}
