// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace AutoCow
{
    public partial class MLModel3
    {
        /// <summary>
        /// model input class for MLModel3.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Livestock_Animal")]
            public string Livestock_Animal { get; set; }

            [ColumnName(@"Age")]
            public float Age { get; set; }

            [ColumnName(@"Feed_Type")]
            public string Feed_Type { get; set; }

            [ColumnName(@"Food_Size_KG")]
            public float Food_Size_KG { get; set; }

            [ColumnName(@"Feed_Frequency")]
            public float Feed_Frequency { get; set; }

            [ColumnName(@"weight")]
            public float Weight { get; set; }

            [ColumnName(@"condition")]
            public string Condition { get; set; }

            [ColumnName(@"insemination")]
            public string Insemination { get; set; }

            [ColumnName(@"type")]
            public string Type { get; set; }

            [ColumnName(@"breed_type")]
            public string Breed_type { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel3.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Livestock_Animal")]
            public string Livestock_Animal { get; set; }

            [ColumnName(@"Age")]
            public float Age { get; set; }

            [ColumnName(@"Feed_Type")]
            public uint Feed_Type { get; set; }

            [ColumnName(@"Food_Size_KG")]
            public float Food_Size_KG { get; set; }

            [ColumnName(@"Feed_Frequency")]
            public float Feed_Frequency { get; set; }

            [ColumnName(@"weight")]
            public float Weight { get; set; }

            [ColumnName(@"condition")]
            public float[] Condition { get; set; }

            [ColumnName(@"insemination")]
            public string Insemination { get; set; }

            [ColumnName(@"type")]
            public string Type { get; set; }

            [ColumnName(@"breed_type")]
            public float[] Breed_type { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public string PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel3.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
