﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace AutoCow
{
    public partial class MLModel2
    {
        /// <summary>
        /// Retrains model using the pipeline generated as part of the training process. For more information on how to load data, see aka.ms/loaddata.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainPipeline(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"Age", @"Age"),new InputOutputColumnPair(@"Temperature", @"Temperature")})      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"Symptom_1",outputColumnName:@"Symptom_1"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"Symptom_2",outputColumnName:@"Symptom_2"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"Symptom_3",outputColumnName:@"Symptom_3"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"Age",@"Temperature",@"Symptom_1",@"Symptom_2",@"Symptom_3"}))      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(outputColumnName:@"Disease",inputColumnName:@"Disease"))      
                                    .Append(mlContext.Transforms.NormalizeMinMax(@"Features", @"Features"))      
                                    .Append(mlContext.MulticlassClassification.Trainers.OneVersusAll(binaryEstimator: mlContext.BinaryClassification.Trainers.LbfgsLogisticRegression(new LbfgsLogisticRegressionBinaryTrainer.Options(){L1Regularization=1.004183F,L2Regularization=63.99987F,LabelColumnName=@"Disease",FeatureColumnName=@"Features"}), labelColumnName:@"Disease"))      
                                    .Append(mlContext.Transforms.Conversion.MapKeyToValue(outputColumnName:@"PredictedLabel",inputColumnName:@"PredictedLabel"));

            return pipeline;
        }
    }
}
