// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace AutoCow
{
    public partial class MLModel
    {
        /// <summary>
        /// model input class for MLModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"id")]
            public float Id { get; set; }

            [ColumnName(@"date")]
            public DateTime Date { get; set; }

            [ColumnName(@"milk")]
            public float Milk { get; set; }

            [ColumnName(@"temperature")]
            public float Temperature { get; set; }

            [ColumnName(@"insemination")]
            public string Insemination { get; set; }

            [ColumnName(@"disease")]
            public string Disease { get; set; }

            [ColumnName(@"condition")]
            public string Condition { get; set; }

            [ColumnName(@"weight")]
            public float Weight { get; set; }

            [ColumnName(@"type")]
            public string Type { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"id")]
            public float Id { get; set; }

            [ColumnName(@"date")]
            public DateTime Date { get; set; }

            [ColumnName(@"milk")]
            public float Milk { get; set; }

            [ColumnName(@"temperature")]
            public float Temperature { get; set; }

            [ColumnName(@"insemination")]
            public float[] Insemination { get; set; }

            [ColumnName(@"disease")]
            public float[] Disease { get; set; }

            [ColumnName(@"condition")]
            public uint Condition { get; set; }

            [ColumnName(@"weight")]
            public float Weight { get; set; }

            [ColumnName(@"type")]
            public string Type { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public string PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
